In [2]:
import tensorflow as tf
import numpy as np

In [3]:
tf.__version__

'2.0.0'

In [4]:
a = np.random.random((4, 8, 12))

In [6]:
a.shape

(4, 8, 12)

In [13]:
a[range(a.shape[0])*8,range(a.shape[1]), :].shape

TypeError: unsupported operand type(s) for *: 'range' and 'int'

In [14]:
input_tf = tf.Variable([ [9.968594,  8.655439,  0.,        0.       ],
                         [0.,        8.3356,    0.,        8.8974   ],
                         [0.,        0.,        6.103182,  7.330564 ],
                         [6.609862,  0.,        3.0614321, 0.       ],
                         [9.497023,  0.,        3.8914037, 0.       ],
                         [0.,        8.457685,  8.602337,  0.       ],
                         [0.,        0.,        5.826657,  8.283971 ],
                         [0.,        0.,        0.,        0.       ]])
rows_tf = tf.constant (
[[1, 2, 5],
 [1, 2, 5],
 [1, 2, 5],
 [1, 4, 6],
 [1, 4, 6],
 [2, 3, 6],
 [2, 3, 6],
 [2, 4, 7]])
columns_tf = tf.constant(
[[1],
 [2],
 [3],
 [2],
 [3],
 [2],
 [3],
 [2]])
rows_tf = tf.reshape(rows_tf, shape=[-1, 1])
columns_tf = tf.reshape(
    tf.tile(columns_tf, multiples=[1, 3]), 
    shape=[-1, 1])
sparse_indices = tf.reshape(
    tf.concat([rows_tf, columns_tf], axis=-1), 
    shape=[-1, 2])

v = tf.gather_nd(input_tf, sparse_indices)
v = tf.reshape(v, [-1, 3])


In [18]:
rows_tf

<tf.Tensor: id=11, shape=(24, 1), dtype=int32, numpy=
array([[1],
       [2],
       [5],
       [1],
       [2],
       [5],
       [1],
       [2],
       [5],
       [1],
       [4],
       [6],
       [1],
       [4],
       [6],
       [2],
       [3],
       [6],
       [2],
       [3],
       [6],
       [2],
       [4],
       [7]], dtype=int32)>

In [21]:
columns_tf

<tf.Tensor: id=15, shape=(24, 1), dtype=int32, numpy=
array([[1],
       [1],
       [1],
       [2],
       [2],
       [2],
       [3],
       [3],
       [3],
       [2],
       [2],
       [2],
       [3],
       [3],
       [3],
       [2],
       [2],
       [2],
       [3],
       [3],
       [3],
       [2],
       [2],
       [2]], dtype=int32)>

In [22]:
sparse_indices

<tf.Tensor: id=19, shape=(24, 2), dtype=int32, numpy=
array([[1, 1],
       [2, 1],
       [5, 1],
       [1, 2],
       [2, 2],
       [5, 2],
       [1, 3],
       [2, 3],
       [5, 3],
       [1, 2],
       [4, 2],
       [6, 2],
       [1, 3],
       [4, 3],
       [6, 3],
       [2, 2],
       [3, 2],
       [6, 2],
       [2, 3],
       [3, 3],
       [6, 3],
       [2, 2],
       [4, 2],
       [7, 2]], dtype=int32)>

In [23]:
v

<tf.Tensor: id=22, shape=(8, 3), dtype=float32, numpy=
array([[8.3356   , 0.       , 8.457685 ],
       [0.       , 6.103182 , 8.602337 ],
       [8.8974   , 7.330564 , 0.       ],
       [0.       , 3.8914037, 5.826657 ],
       [8.8974   , 0.       , 8.283971 ],
       [6.103182 , 3.0614321, 5.826657 ],
       [7.330564 , 0.       , 8.283971 ],
       [6.103182 , 3.8914037, 0.       ]], dtype=float32)>

In [225]:
batch_dims = 1
#indices = [[[0, 0], [0,1]], [[0, 0], [0,1]]]
indices = [[[0], [2], [3]]]
params = [[['a0', 'b0', 'c0'], ['d0', 'e0', 'f0'], ['g0', 'h0', 'i0'], ['j0', 'k0', 'l0']],
          [['a1', 'b1', 'c1'], ['d1', 'e1', 'f1'], ['g1', 'h1', 'i1'], ['j1', 'k1', 'l1']],
          [['a2', 'b2', 'c2'], ['d2', 'e2', 'f2'], ['g2', 'h2', 'i2'], ['j2', 'k2', 'l2']],
          [['a3', 'b3', 'c3'], ['d3', 'e3', 'f3'], ['g3', 'h3', 'i3'], ['j3', 'k3', 'l3']],
          [['a3', 'b3', 'c3'], ['d3', 'e3', 'f3'], ['g3', 'h3', 'i3'], ['j4', 'k4', 'l4']]]
output = [['c0'], ['b1']]

In [226]:
tf_params = tf.convert_to_tensor(params)
tf_params

<tf.Tensor: id=3151, shape=(5, 4, 3), dtype=string, numpy=
array([[[b'a0', b'b0', b'c0'],
        [b'd0', b'e0', b'f0'],
        [b'g0', b'h0', b'i0'],
        [b'j0', b'k0', b'l0']],

       [[b'a1', b'b1', b'c1'],
        [b'd1', b'e1', b'f1'],
        [b'g1', b'h1', b'i1'],
        [b'j1', b'k1', b'l1']],

       [[b'a2', b'b2', b'c2'],
        [b'd2', b'e2', b'f2'],
        [b'g2', b'h2', b'i2'],
        [b'j2', b'k2', b'l2']],

       [[b'a3', b'b3', b'c3'],
        [b'd3', b'e3', b'f3'],
        [b'g3', b'h3', b'i3'],
        [b'j3', b'k3', b'l3']],

       [[b'a3', b'b3', b'c3'],
        [b'd3', b'e3', b'f3'],
        [b'g3', b'h3', b'i3'],
        [b'j4', b'k4', b'l4']]], dtype=object)>

In [227]:
tf_indices = tf.convert_to_tensor(indices)
tf_indices =tf.tile(tf_indices, tf.constant([5, 1, 1]))
tf_indices

<tf.Tensor: id=3154, shape=(5, 3, 1), dtype=int32, numpy=
array([[[0],
        [2],
        [3]],

       [[0],
        [2],
        [3]],

       [[0],
        [2],
        [3]],

       [[0],
        [2],
        [3]],

       [[0],
        [2],
        [3]]], dtype=int32)>

In [230]:
tf.gather_nd(tf_params, tf_indices, batch_dims=1)

<tf.Tensor: id=3307, shape=(5, 3, 3), dtype=string, numpy=
array([[[b'a0', b'b0', b'c0'],
        [b'g0', b'h0', b'i0'],
        [b'j0', b'k0', b'l0']],

       [[b'a1', b'b1', b'c1'],
        [b'g1', b'h1', b'i1'],
        [b'j1', b'k1', b'l1']],

       [[b'a2', b'b2', b'c2'],
        [b'g2', b'h2', b'i2'],
        [b'j2', b'k2', b'l2']],

       [[b'a3', b'b3', b'c3'],
        [b'g3', b'h3', b'i3'],
        [b'j3', b'k3', b'l3']],

       [[b'a3', b'b3', b'c3'],
        [b'g3', b'h3', b'i3'],
        [b'j4', b'k4', b'l4']]], dtype=object)>

# Slicing example

In [297]:
@tf.function 
def slicing_list(tensor, indices, axis=1):
    """
    Slice some indices as numpy.
    Ex: Tensor[:, indices, :] with axis=1
    """
    tensor_shape = tf.shape(tensor)
    indices = tf.convert_to_tensor(indices)
    for i in range(tensor_shape.shape[0]):
        if i<axis:
            indices = tf.expand_dims(indices, 0)
        elif i>axis:
            indices = tf.expand_dims(indices, -1)
    multiplier = tf.stack([tensor_shape[0], 1, 1], axis=-1)
    indices = tf.tile(indices, multiplier)
    print(indices)
    output = tf.gather_nd(tensor, indices, batch_dims=1)
    return output

In [298]:
output

<tf.Tensor: id=4375, shape=(5, 3, 3), dtype=string, numpy=
array([[[b'd0', b'e0', b'f0'],
        [b'a0', b'b0', b'c0'],
        [b'j0', b'k0', b'l0']],

       [[b'd1', b'e1', b'f1'],
        [b'a1', b'b1', b'c1'],
        [b'j1', b'k1', b'l1']],

       [[b'd2', b'e2', b'f2'],
        [b'a2', b'b2', b'c2'],
        [b'j2', b'k2', b'l2']],

       [[b'd3', b'e3', b'f3'],
        [b'a3', b'b3', b'c3'],
        [b'j3', b'k3', b'l3']],

       [[b'd3', b'e3', b'f3'],
        [b'a3', b'b3', b'c3'],
        [b'j4', b'k4', b'l4']]], dtype=object)>